namespace MetaheuristicsPlatform.Catalog;

public static class MetaheuristicCatalog
{
    private static readonly MetaheuristicCatalogEntry[] Entries =
    [
        new(
            "particle-swarm",
            "Particle Swarm Optimization",
            "ParticleSwarmOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(ND) per iteration for the canonical graphless fast path; topology/social policies may add overhead",
            "O(ND)",
            "Continuous bounded search spaces; generic platform infrastructure also supports alternative social/topology policies",
            false,
            "src/MetaheuristicsPlatform/Algorithms/PSO/ParticleSwarmOptimizer.cs",
            "Kennedy & Eberhart (1995), Particle Swarm Optimization, IEEE ICNN; Clerc & Kennedy (2002), The particle swarm — explosion, stability, and convergence in a multidimensional complex space, IEEE TEC 6(1), 58–73",
            "10.1109/4235.985692",
            "Flat particle-major buffers, deterministic target-owned RNG streams, graphless fully-connected canonical fast path, calibrated movement/evaluation parallelism."),
        new(
            "artificial-bee-colony-karaboga-basturk-2007",
            "Artificial Bee Colony",
            "ArtificialBeeColonyOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(SD) per complete cycle plus objective-evaluation cost",
            "O(SD+S)",
            "Bounded continuous derivative-free optimization with probabilistic recruitment and explicit source abandonment",
            false,
            "src/MetaheuristicsPlatform/Algorithms/ArtificialBeeColony/ArtificialBeeColonyOptimizer.cs",
            "Karaboga & Basturk (2007), A Powerful and Efficient Algorithm for Numerical Function Optimization: Artificial Bee Colony (ABC) Algorithm, Journal of Global Optimization 39(3), 459-471",
            "10.1007/s10898-007-9149-x",
            "Canonical employed/onlooker/scout phases, one-coordinate source perturbation, proportional onlooker selection, greedy replacement, abandonment trials and exact OptimizationContext accounting."),
        new(
            "firefly-algorithm-yang-2009",
            "Firefly Algorithm",
            "FireflyOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(N^2*D) pairwise movement work per complete iteration plus up to O(N^2) objective evaluations",
            "O(N*D)",
            "Bounded continuous derivative-free multimodal optimization with distance-dependent attraction",
            false,
            "src/MetaheuristicsPlatform/Algorithms/Firefly/FireflyOptimizer.cs",
            "Yang (2009), Firefly Algorithms for Multimodal Optimization, Stochastic Algorithms: Foundations and Applications, LNCS 5792, 169-178",
            "10.1007/978-3-642-04944-6_14",
            "Sequential objective-sense-symmetric pairwise attraction with beta(r)=beta0*exp(-gamma*r^2), additive alpha*(U-1/2) randomization, bounded repair and exact OptimizationContext accounting."),
        new(
            "harmony-search-geem-kim-loganathan-2001",
            "Harmony Search",
            "HarmonySearchOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) initialization; O(D+H) per improvisation plus one objective evaluation",
            "O(H*D)",
            "Bounded continuous derivative-free optimization using Harmony Memory consideration, pitch adjustment and worst-harmony replacement",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/HarmonySearchOptimizer.cs",
            "Geem, Kim & Loganathan (2001), A New Heuristic Optimization Algorithm: Harmony Search, SIMULATION 76(2), 60-68",
            "10.1177/003754970107600201",
            "Canonical fixed-parameter HMS/HMCR/PAR/absolute-bandwidth improvisation, objective-sense-symmetric worst-harmony replacement and exact OptimizationContext accounting."),        new(
            "improved-harmony-search-mahdavi-fesanghary-damangir-2007",
            "Improved Harmony Search",
            "ImprovedHarmonySearchOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) initialization; O(D+H) per improvisation plus O(1) PAR/bw scheduling and one objective evaluation",
            "O(H*D)",
            "Bounded continuous derivative-free optimization using fixed HMCR with linearly increasing PAR and exponentially decreasing bandwidth",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/ImprovedHarmonySearchOptimizer.cs",
            "Mahdavi, Fesanghary & Damangir (2007), An improved harmony search algorithm for solving optimization problems, Applied Mathematics and Computation 188(2), 1567-1579",
            "10.1016/j.amc.2006.11.033",
            "Canonical IHS parameter control: fixed HMCR, published linear PAR schedule, published exponential absolute-bandwidth schedule, HS improvisation and strict worst-harmony replacement."),        new(
            "global-best-harmony-search-omran-mahdavi-2008",
            "Global-best Harmony Search",
            "GlobalBestHarmonySearchOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) initialization; O(D+H) per improvisation plus O(1) dynamic PAR and one objective evaluation",
            "O(H*D)",
            "Bounded continuous derivative-free optimization using fixed HMCR, dynamic PAR and bandwidth-free global-best cross-coordinate pitch adjustment",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/GlobalBestHarmonySearchOptimizer.cs",
            "Omran & Mahdavi (2008), Global-best harmony search, Applied Mathematics and Computation 198(2), 643-656",
            "10.1016/j.amc.2007.09.004",
            "Canonical GHS: dynamic IHS-style PAR, no bandwidth parameter, pitch adjustment x_i^new=x_k^best with random decision-variable k, strict worst-harmony replacement and explicit bounded-platform repair."),        new(
            "self-adaptive-global-best-harmony-search-pan-suganthan-tasgetiren-liang-2010",
            "Self-Adaptive Global-best Harmony Search",
            "SelfAdaptiveGlobalBestHarmonySearchOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) initialization; O(D+H) expected per improvisation plus periodic O(LP) success-parameter learning",
            "O(H*D+LP)",
            "Bounded continuous derivative-free optimization using successful-parameter learning, truncated-normal HMCR/PAR sampling, piecewise dynamic bandwidth and corresponding-coordinate global-best pitch adjustment",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/SelfAdaptiveGlobalBestHarmonySearchOptimizer.cs",
            "Pan, Suganthan, Tasgetiren & Liang (2010), A self-adaptive global best harmony search algorithm for continuous optimization problems, Applied Mathematics and Computation 216(3), 830-848",
            "10.1016/j.amc.2010.01.088",
            "Canonical SGHS scientific controls with successful HMCR/PAR learning, fixed Gaussian standard deviations, bounded normal sampling, piecewise BW and x_i^new=x_i^best pitch exploitation."),        new(
            "novel-global-harmony-search-zou-gao-wu-li-2010",
            "Novel Global Harmony Search",
            "NovelGlobalHarmonySearchOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) initialization; O(H+D) per improvisation plus one objective evaluation",
            "O(H*D)",
            "Bounded continuous derivative-free optimization using reflected-best position updating, low-probability genetic mutation and unconditional worst-harmony replacement",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/NovelGlobalHarmonySearchOptimizer.cs",
            "Zou, Gao, Wu, Li & Li (2010), A novel global harmony search algorithm for reliability problems, Computers & Industrial Engineering 58(2), 307-316",
            "10.1016/j.cie.2009.11.003",
            "Canonical NGHS: no HMCR/PAR/BW, reflected endpoint x_R=clip(2*x_best-x_worst), interpolation from x_worst toward x_R, coordinate mutation with p_m, and unconditional replacement of the current worst harmony."),        new(
            "parameter-setting-free-harmony-search-geem-sim-2010",
            "Parameter-Setting-Free Harmony Search",
            "ParameterSettingFreeHarmonySearchOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) memory plus O(H*D) adaptive-rate recomputation per performance improvisation and one objective evaluation",
            "O(H*D)",
            "Bounded continuous derivative-free optimization with an Operation Type Matrix that learns variable-specific HMCR/PAR from surviving random, memory and pitch operations",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/ParameterSettingFreeHarmonySearchOptimizer.cs",
            "Geem & Sim (2010), Parameter-setting-free harmony search algorithm, Applied Mathematics and Computation 217(8), 3881-3889",
            "10.1016/j.amc.2010.09.049",
            "Conventional PSF-HS: random tuning, HMCR=PAR=0.5 rehearsal, OTM-coupled strict replacement, then per-variable HMCR=count(Memory or Pitch)/HMS and PAR=count(Pitch)/count(Memory or Pitch)."),        new(
            "advanced-parameter-setting-free-harmony-search-iteration-jeong-park-geem-sim-2020",
            "Advanced Parameter-Setting-Free Harmony Search - Iteration Scheme",
            "AdvancedParameterSettingFreeHarmonySearchIterationOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) initialization; O(H+D) per improvisation plus one objective evaluation",
            "O(H*D)",
            "Bounded continuous derivative-free optimization with sigmoid iteration/dimension HMCR and dimension-aware PAR without OTM",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/AdvancedParameterSettingFreeHarmonySearchIterationOptimizer.cs",
            "Jeong, Park, Geem & Sim (2020), Advanced Parameter-Setting-Free Harmony Search Algorithm, Applied Sciences 10(7), 2586",
            "10.3390/app10072586",
            "Iteration APSF-HS only: HMCR=0.5+0.5*sigmoid(10*t/NI-5/log(D)); PAR=HMCR*sigmoid(4/D-2); fixed problem-scale bandwidth; no OTM and no object-dependent scheme."),        new(
            "advanced-parameter-setting-free-harmony-search-object-jeong-park-geem-sim-2020",
            "Advanced Parameter-Setting-Free Harmony Search - Object Scheme",
            "AdvancedParameterSettingFreeHarmonySearchObjectOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) memory; O(H+D) per improvisation; O(H) HM-mean updates; Equation (9) at HMS block boundaries",
            "O(H*D)",
            "Bounded continuous minimization with a known target objective, target-dependent HMCR/PAR and object-only adaptive pitch bandwidth",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/AdvancedParameterSettingFreeHarmonySearchObjectOptimizer.cs",
            "Jeong, Park, Geem & Sim (2020), Advanced Parameter-Setting-Free Harmony Search Algorithm, Applied Sciences 10(7), 2586",
            "10.3390/app10072586",
            "Object APSF-HS: Equations (7),(8),(9); minimization-only target semantics; first-HMS rehearsal; no OTM; adaptive bandwidth by HM-mean progress."),        new(
            "differential-harmony-search-chakraborty-roy-das-jain-abraham-2009",
            "Differential Harmony Search",
            "DifferentialHarmonySearchOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) memory plus variant-specific improvisation work",
            "O(H*D)",
            "Bounded continuous derivative-free minimization or maximization.",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/DifferentialHarmonySearchOptimizer.cs",
            "P. Chakraborty, G. G. Roy, S. Das, D. Jain, A. Abraham (2009), An Improved Harmony Search Algorithm with Differential Mutation Operator, Fundamenta Informaticae 95(4), 401-426",
            "10.3233/FI-2009-157",
            "Exact DHS structure: HS memory/random intermediate vector followed by DE/rand/1-style differential mutation with one F~U[0,1] and two distinct HM members; strict objective-sense replacement."),
        new(
            "exploratory-harmony-search-das-mukhopadhyay-roy-abraham-panigrahi-2011",
            "Exploratory Harmony Search",
            "ExploratoryHarmonySearchOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) memory plus variant-specific improvisation work",
            "O(H*D)",
            "Bounded continuous derivative-free global numerical optimization.",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/ExploratoryHarmonySearchOptimizer.cs",
            "S. Das, A. Mukhopadhyay, A. Roy, A. Abraham, B. K. Panigrahi (2011), Exploratory Power of the Harmony Search Algorithm: Analysis and Improvements for Global Numerical Optimization, IEEE Transactions on Systems, Man, and Cybernetics, Part B 41(1), 89-106",
            "10.1109/TSMCB.2010.2046035",
            "EHS keeps canonical HS memory consideration/random selection and sets per-coordinate fine-tuning width FW_i=k*sqrt(Var(HM_i)), recomputed from the current Harmony Memory."),
        new(
            "improved-harmony-search-differential-mutation-yong-liu-zhang-feng-2012",
            "Improved Harmony Search Based on Differential Mutation Operator",
            "ImprovedHarmonySearchDifferentialMutationOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) memory plus variant-specific improvisation work",
            "O(H*D)",
            "Bounded continuous derivative-free minimization.",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/ImprovedHarmonySearchDifferentialMutationOptimizer.cs",
            "L. Yong, S. Liu, J. Zhang, Q. Feng (2012), Theoretical and Empirical Analyses of an Improved Harmony Search Algorithm Based on Differential Mutation Operator, Journal of Applied Mathematics 2012, Article 147950",
            "10.1155/2012/147950",
            "IHSDE memory branch chooses j,r1,r2 distinct and generates x'_i=x^j_i+F(x^r1_i-x^r2_i), F~U[0.6,1]; random branch remains uniform over bounds."),
        new(
            "novel-self-adaptive-harmony-search-luo-2013",
            "Novel Self-Adaptive Harmony Search",
            "NovelSelfAdaptiveHarmonySearchOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) memory plus variant-specific improvisation work",
            "O(H*D)",
            "Bounded continuous derivative-free minimization.",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/NovelSelfAdaptiveHarmonySearchOptimizer.cs",
            "K. Luo (2013), A Novel Self-Adaptive Harmony Search Algorithm, Journal of Applied Mathematics 2013, Article 653749",
            "10.1155/2013/653749",
            "NSHS dimension-derived HMCR, no PAR, fitness-standard-deviation threshold 0.0001, best-to-worst narrow randomization under low diversity and the paper's two perturbation branches."),
        new(
            "adaptive-harmony-search-differential-evolution-zhao-li-hao-liu-yuan-2020",
            "Adaptive Harmony Search with Differential Evolution",
            "AdaptiveHarmonySearchDifferentialEvolutionOptimizer",
            "other-metaheuristics",
            "Other / music-inspired methods",
            "O(H*D) memory plus variant-specific improvisation work",
            "O(H*D)",
            "Bounded continuous derivative-free minimization.",
            false,
            "src/MetaheuristicsPlatform/Algorithms/HarmonySearch/AdaptiveHarmonySearchDifferentialEvolutionOptimizer.cs",
            "X. Zhao, R. Li, J. Hao, Z. Liu, J. Yuan (2020), A New Differential Mutation Based Adaptive Harmony Search Algorithm for Global Optimization, Applied Sciences 10(8), 2916",
            "10.3390/app10082916",
            "Exact paper-defined aHSDE mechanism bundle: DE/best/2 pitch adjustment, Gaussian PAR/F sampling around learned means, successful-parameter weighted Lehmer updates, and linear HMS reduction against NFE."),
        new(
            "ant-system-dorigo-maniezzo-colorni-1996",
            "Ant System - Dorigo-Maniezzo-Colorni",
            "AntSystemOptimizer<TSolution,TComponent,TPheromoneKey,TEnumerator>",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(sum over ants and construction steps of feasible-candidate scans) per iteration, plus objective-evaluation cost",
            "O(|P| + colony solution/key-path storage) with O(1) lazy global evaporation",
            "Finite constructive binary, integer, permutation, combinatorial and mixed discrete search spaces with typed feasibility, heuristic-information and pheromone-key contracts",
            true,
            "src/MetaheuristicsPlatform/Algorithms/AntColony/AntSystemOptimizer.cs",
            "Dorigo, Maniezzo & Colorni (1996), Ant System: Optimization by a Colony of Cooperating Agents, IEEE Transactions on Systems, Man, and Cybernetics, Part B 26(1), 29-41",
            "10.1109/3477.484436",
            "Generic proportional pheromone/heuristic construction, log-space Gumbel-max categorical sampling, sparse lazy exact evaporation, all-ant global reinforcement, explicit deposit policies and common OptimizationContext accounting."),
        new(
            "ant-colony-system-dorigo-gambardella-1997",
            "Ant Colony System - Dorigo-Gambardella",
            "AntColonySystemOptimizer<TSolution,TComponent,TPheromoneKey,TEnumerator>",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(sum over ants and construction steps of feasible-candidate scans) per iteration, plus objective-evaluation cost",
            "O(|P| + best path + colony construction workspace)",
            "Finite constructive combinatorial search spaces with typed feasibility, heuristic information and pheromone keys",
            true,
            "src/MetaheuristicsPlatform/Algorithms/AntColony/AntColonySystemOptimizer.cs",
            "Dorigo & Gambardella (1997), Ant Colony System: A Cooperative Learning Approach to the Traveling Salesman Problem, IEEE Transactions on Evolutionary Computation 1(1), 53-66",
            "10.1109/4235.585892",
            "Generic ACS pseudo-random proportional transition, immediate local pheromone update and best-so-far global reinforcement over the shared ACO construction engine."),
        new(
            "max-min-ant-system-stutzle-hoos-2000",
            "MAX-MIN Ant System - Stutzle-Hoos",
            "MaxMinAntSystemOptimizer<TSolution,TComponent,TPheromoneKey,TEnumerator>",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(sum over ants and construction steps of feasible-candidate scans) per iteration, plus objective-evaluation cost",
            "O(|P| + best path + colony construction workspace) with bounded sparse lazy pheromone memory",
            "Finite constructive combinatorial search spaces with typed feasibility, heuristic information and pheromone keys",
            true,
            "src/MetaheuristicsPlatform/Algorithms/AntColony/MaxMinAntSystemOptimizer.cs",
            "Stutzle & Hoos (2000), MAX-MIN Ant System, Future Generation Computer Systems 16(8), 889-914",
            "10.1016/S0167-739X(00)00043-1",
            "Generic MMAS best-only reinforcement, explicit pheromone bounds, iteration-best/best-so-far source selection and optional stagnation restart over the shared ACO foundation."),
        new(
            "cma-es-hansen-ostermeier-2001",
            "Covariance Matrix Adaptation Evolution Strategy",
            "CmaEsOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(lambda*n^2+n^3) per complete generation plus objective-evaluation cost",
            "O(lambda*n+n^2)",
            "Bounded continuous derivative-free optimization; especially non-separable and ill-conditioned objectives",
            false,
            "src/MetaheuristicsPlatform/Algorithms/CMAES/CmaEsOptimizer.cs",
            "Hansen & Ostermeier (2001), Completely Derandomized Self-Adaptation in Evolution Strategies, Evolutionary Computation 9(2), 159-195",
            "10.1162/106365601750190398",
            "Canonical full-covariance CMA-ES with positive logarithmic recombination, evolution-path cumulation, cumulative step-size adaptation, rank-one/rank-mu covariance updates and stable symmetric eigendecomposition."),
        new(
            "active-cma-es-hansen-ros-2010",
            "Active CMA-ES",
            "ActiveCmaEsOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(lambda*n^2+n^3) per complete generation plus objective-evaluation cost",
            "O(lambda*n+n^2)",
            "Bounded continuous derivative-free optimization with full dependency learning and weighted negative covariance adaptation",
            false,
            "src/MetaheuristicsPlatform/Algorithms/CMAES/ActiveCmaEsOptimizer.cs",
            "Hansen & Ros (2010), Benchmarking a Weighted Negative Covariance Matrix Update on the BBOB-2010 Noiseless Testbed",
            "10.1145/1830761.1830788",
            "Weighted active covariance adaptation with normalized negative unsuccessful directions, positive logarithmic parent recombination, CSA and positive-definite covariance reconstruction."),
        new(
            "separable-cma-es-ros-hansen-2008",
            "Separable CMA-ES",
            "SeparableCmaEsOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(lambda*n) per complete generation plus objective-evaluation cost",
            "O(lambda*n+n)",
            "High-dimensional bounded continuous derivative-free optimization when coordinate-wise covariance is appropriate",
            false,
            "src/MetaheuristicsPlatform/Algorithms/CMAES/SeparableCmaEsOptimizer.cs",
            "Ros & Hansen (2008), A Simple Modification in CMA-ES Achieving Linear Time and Space Complexity, PPSN X, 296-305",
            "10.1007/978-3-540-87700-4_30",
            "Diagonal covariance adaptation with the Ros-Hansen accelerated covariance learning rate, CSA, evolution paths and linear internal time/space complexity."),
        new(
            "ipop-cma-es-auger-hansen-2005",
            "IPOP-CMA-ES",
            "IpopCmaEsOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "Sum over restart runs of O(lambda_r*n^2+n^3) per complete generation plus objective-evaluation cost",
            "O(max_r(lambda_r*n)+n^2)",
            "Multimodal bounded continuous derivative-free optimization with unknown useful population scale",
            false,
            "src/MetaheuristicsPlatform/Algorithms/CMAES/IpopCmaEsOptimizer.cs",
            "Auger & Hansen (2005), A Restart CMA Evolution Strategy with Increasing Population Size, IEEE CEC, 1769-1776",
            "10.1109/CEC.2005.1554902",
            "One global OptimizationContext across geometrically increasing-population CMA-ES restarts, preserving exact evaluation/stopping accounting."),
        new(
            "bipop-cma-es-hansen-2009",
            "BIPOP-CMA-ES",
            "BipopCmaEsOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "Sum over large/small restart runs of O(lambda*n^2+n^3) per complete generation plus objective-evaluation cost",
            "O(max_run(lambda*n)+n^2)",
            "Multimodal bounded continuous derivative-free optimization requiring both large and repeated small population regimes",
            false,
            "src/MetaheuristicsPlatform/Algorithms/CMAES/BipopCmaEsOptimizer.cs",
            "Hansen (2009), Benchmarking a BI-Population CMA-ES on the BBOB-2009 Function Testbed, GECCO Companion, 2389-2396",
            "10.1145/1570256.1570333",
            "Evaluation-budget-balanced IPOP large-population and randomized small-population restart regimes under one global OptimizationContext."),
        new(
            "cross-entropy-continuous-kroese-porotsky-rubinstein-2006",
            "Cross-Entropy Method - Continuous Optimization",
            "ContinuousCrossEntropyOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(N*D + N log N) per complete iteration plus objective-evaluation cost",
            "O(N*D + N)",
            "Bounded continuous derivative-free multi-extremal optimization using an adaptive diagonal normal sampling model",
            false,
            "src/MetaheuristicsPlatform/Algorithms/CrossEntropy/ContinuousCrossEntropyOptimizer.cs",
            "Kroese, Porotsky & Rubinstein (2006), The Cross-Entropy Method for Continuous Multi-Extremal Optimization, Methodology and Computing in Applied Probability 8(3), 383-407",
            "10.1007/s11009-006-9753-0",
            "Independent normal sampling, elite maximum-likelihood mean/standard-deviation estimates, fixed mean smoothing, dynamic sigma smoothing and exact partial-iteration OptimizationContext accounting."),
        new(
            "differential-evolution",
            "Differential Evolution",
            "DifferentialEvolutionOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(ND) per generation for classical mutation/crossover, plus objective-evaluation cost",
            "O(ND)",
            "Continuous bounded search spaces",
            false,
            "src/MetaheuristicsPlatform/Algorithms/DE/DifferentialEvolutionOptimizer.cs",
            "Storn & Price (1997), Differential Evolution — A Simple and Efficient Heuristic for Global Optimization over Continuous Spaces, Journal of Global Optimization 11(4), 341–359",
            "10.1023/A:1008202821328",
            "Flat parent/trial buffers; classical mutation and crossover strategies; deterministic per-target RNG; calibrated variation and independent evaluation parallelism."),
        new(
            "jde-brest-2006",
            "jDE — Self-Adaptive Differential Evolution",
            "SelfAdaptiveDifferentialEvolutionOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(ND) per generation plus objective-evaluation cost",
            "O(ND + N)",
            "Continuous bounded search spaces; canonical DE/rand/1/bin self-adaptation",
            false,
            "src/MetaheuristicsPlatform/Algorithms/DE/Adaptive/SelfAdaptiveDifferentialEvolutionOptimizer.cs",
            "Brest et al. (2006), Self-Adapting Control Parameters in Differential Evolution: A Comparative Study on Numerical Benchmark Problems, IEEE TEC 10(6), 646–657",
            "10.1109/TEVC.2006.872133",
            "Per-individual inherited F_i/CR_i proposals; trial parameters are committed only after strict successful selection."),
        new(
            "jade-2009",
            "JADE",
            "JadeOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(ND + N log N) per generation plus objective-evaluation cost",
            "O(ND) population plus O(ND) optional archive",
            "Continuous bounded search spaces",
            false,
            "src/MetaheuristicsPlatform/Algorithms/DE/Adaptive/JadeOptimizer.cs",
            "Zhang & Sanderson (2009), JADE: Adaptive Differential Evolution With Optional External Archive, IEEE TEC 13(5), 945–958",
            "10.1109/TEVC.2009.2014613",
            "current-to-pbest/1/bin, optional external archive, Cauchy F sampling, normal CR sampling and success-mean adaptation."),
        new(
            "shade-2013",
            "SHADE",
            "ShadeOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(ND + N log N) per generation plus objective-evaluation cost",
            "O(ND + H)",
            "Continuous bounded search spaces",
            false,
            "src/MetaheuristicsPlatform/Algorithms/DE/Adaptive/ShadeOptimizer.cs",
            "Tanabe & Fukunaga (2013), Success-History Based Parameter Adaptation for Differential Evolution, IEEE CEC, 71–78",
            "10.1109/CEC.2013.6557555",
            "Historical memories M_F/M_CR, random memory slot per target, improvement-weighted success learning and external archive."),
        new(
            "lshade-2014",
            "L-SHADE",
            "LShadeOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(N_kD + N_k log N_k) at generation k plus objective-evaluation cost",
            "O(N_init D + H)",
            "Continuous bounded search spaces with an evaluation budget driving LPSR",
            false,
            "src/MetaheuristicsPlatform/Algorithms/DE/Adaptive/LShadeOptimizer.cs",
            "Tanabe & Fukunaga (2014), Improving the Search Performance of SHADE Using Linear Population Size Reduction, IEEE CEC, 1658–1665",
            "10.1109/CEC.2014.6900380",
            "SHADE 1.1 success-history semantics with linear population-size reduction, fixed physical capacity and shrinking active prefix."),
        new(
            "genetic-algorithm-generational",
            "Generational Genetic Algorithm",
            "GenerationalGeneticAlgorithmOptimizer<TSolution>",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(N(C_S+C_X+C_M+C_f)) per generation without elitism sorting; O(N log N + N(C_S+C_X+C_M+C_f)) with elitism",
            "O(N * |solution|) for owned current/next populations plus representation-specific operator workspace",
            "Any complete-solution representation with compatible initialization, crossover, mutation and cloning",
            true,
            "src/MetaheuristicsPlatform/Algorithms/GeneticAlgorithm/GenerationalGeneticAlgorithmOptimizer.cs",
            "Eiben & Smith (2003), Genetic Algorithms, Introduction to Evolutionary Computing, 37-69; Whitley (1994), A genetic algorithm tutorial; Blickle & Thiele (1996), A Comparison of Selection Schemes used in Evolutionary Algorithms",
            "10.1007/978-3-662-05094-1_3",
            "Generic fixed-size generational replacement with objective-sense symmetric tournament selection, representation-specific crossover/mutation, optional non-reevaluated elitism, strict solution ownership and common OptimizationContext lifecycle."),
        new(
            "memetic-algorithm-moscato-1989",
            "Memetic Algorithm - Moscato",
            "MemeticAlgorithmOptimizer<TSolution>",
            "hybrid-methods",
            "Hybrid / memetic methods",
            "O(N(C_S+C_X+C_M+C_f)+sum C_LS) per generation; ranked local-improvement policies add O(N log N)",
            "O(N * |solution|) plus one owned local-search phenotype and local-search workspace",
            "Any complete-solution representation with compatible GA operators, cloning and an ILocalSearchProcedure<TSolution>",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Memetic/MemeticAlgorithmOptimizer.cs",
            "Moscato (1989), On Evolution, Search, Optimization, Genetic Algorithms and Martial Arts: Towards Memetic Algorithms; Krasnogor & Smith (2005), A Tutorial for Competent Memetic Algorithms: Model, Taxonomy, and Design Issues",
            "10.1109/TEVC.2005.850260",
            "Shared generational GA engine plus pluggable offspring local improvement, Lamarckian/Baldwinian learning, periodic/probabilistic/ranked/adaptive application policies and exact common evaluation accounting."),        new(
            "scatter-search-marti-laguna-glover-2006",
            "Scatter Search",
            "ScatterSearchOptimizer<TSolution>",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(P(C_f+C_I)+P b C_d+P log P) initialization; up to O(b^2(C_C+C_I+C_f+b C_d)) per simple pairwise round",
            "O(P + b) owned solution snapshots plus domain combination/improvement workspace",
            "Any complete-solution representation with domain diversification, distance and combination methods; improvement is optional",
            true,
            "src/MetaheuristicsPlatform/Algorithms/ScatterSearch/ScatterSearchOptimizer.cs",
            "Marti, Laguna & Glover (2006), Principles of scatter search, European Journal of Operational Research 169(2), 359-372; Laguna & Marti (2003), Scatter Search: Methodology and Implementations in C",
            "10.1016/j.ejor.2004.08.004",
            "Five-method generic Scatter Search template with quality/diversity RefSet construction, pairwise-new subset generation, strict distinct quality replacement, objective-sense symmetry and common OptimizationContext lifecycle."),
        new(
            "simulated-annealing-metropolis",
            "Simulated Annealing",
            "SimulatedAnnealingOptimizer<TSolution,TMove,TUndo>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(C_move + C_eval) per attempted transition; O(C_delta) when an exact differential evaluator is available",
            "O(|solution| + |move| + |undo|); no mandatory per-transition solution clone on the reversible path",
            "Any solution representation admitting a stochastic neighborhood and reversible move operator; exact delta evaluation is optional",
            true,
            "src/MetaheuristicsPlatform/Algorithms/SA/SimulatedAnnealingOptimizer.cs",
            "Metropolis et al. (1953), Journal of Chemical Physics 21(6), 1087–1092; Kirkpatrick, Gelatt & Vecchi (1983), Science 220(4598), 671–680",
            "10.1126/science.220.4598.671",
            "Generic reversible trajectory engine, Metropolis acceptance, pluggable cooling schedules, exact-delta fast path and common OptimizationContext lifecycle."),
        new(
            "threshold-accepting-dueck-scheuer-1990",
            "Threshold Accepting",
            "ThresholdAcceptingOptimizer<TSolution,TMove,TUndo>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(C_move + C_eval) per attempted transition; O(C_delta) with an exact move-objective evaluator",
            "O(|solution| + |move| + |undo|); O(1) acceptance state beyond the solution and domain move workspace",
            "Any solution representation admitting a stochastic neighborhood and reversible move operator; exact delta evaluation is optional",
            true,
            "src/MetaheuristicsPlatform/Algorithms/TA/ThresholdAcceptingOptimizer.cs",
            "Dueck & Scheuer (1990), Threshold accepting: A general purpose optimization algorithm appearing superior to simulated annealing, Journal of Computational Physics 90(1), 161-175",
            "10.1016/0021-9991(90)90201-B",
            "Deterministic threshold acceptance over the generic reversible trajectory executor, exact-delta fast path, monotone threshold schedules and common OptimizationContext lifecycle."),        new(
            "great-deluge-dueck-1993",
            "Great Deluge Algorithm",
            "GreatDelugeOptimizer<TSolution,TMove,TUndo>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(C_move + C_eval) per attempted transition; O(C_delta) with an exact move-objective evaluator",
            "O(|solution| + |move| + |undo|); O(1) water-level state beyond domain workspace",
            "Stochastic reversible neighborhoods; exact candidate-objective evaluation is optional",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Acceptance/GreatDelugeOptimizer.cs",
            "Dueck (1993), New Optimization Heuristics: The Great Deluge Algorithm and the Record-to-Record Travel, Journal of Computational Physics 104(1), 86-92",
            "10.1006/jcph.1993.1010",
            "Classical absolute water-level acceptance, one positive linear rain-speed parameter, exact-delta reversible execution and visited-state best accounting."),
        new(
            "record-to-record-travel-dueck-1993",
            "Record-to-Record Travel",
            "RecordToRecordTravelOptimizer<TSolution,TMove,TUndo>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(C_move + C_eval) per attempted transition; O(C_delta) with an exact move-objective evaluator",
            "O(|solution| + |move| + |undo|); O(1) record-deviation state beyond domain workspace",
            "Stochastic reversible neighborhoods; exact candidate-objective evaluation is optional",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Acceptance/RecordToRecordTravelOptimizer.cs",
            "Dueck (1993), New Optimization Heuristics: The Great Deluge Algorithm and the Record-to-Record Travel, Journal of Computational Physics 104(1), 86-92",
            "10.1006/jcph.1993.1010",
            "Classical fixed absolute deviation around the best accepted record, exact-delta reversible execution and visited-state best accounting."),        new(
            "late-acceptance-hill-climbing-burke-bykov-2017",
            "Late Acceptance Hill Climbing",
            "LateAcceptanceHillClimbingOptimizer<TSolution,TMove,TUndo>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(C_move + C_eval) per attempted transition; O(C_delta) with an exact move-objective evaluator",
            "O(|solution| + L) for circular objective history of length L, beyond domain move workspace",
            "Any solution representation admitting a stochastic neighborhood and reversible move operator; exact delta evaluation is optional",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Acceptance/LateAcceptanceHillClimbingOptimizer.cs",
            "Burke & Bykov (2017), The late acceptance Hill-Climbing heuristic, European Journal of Operational Research 258(1), 70-78",
            "10.1016/j.ejor.2016.07.012",
            "Final Burke-Bykov history-reference acceptance with non-worsening hill-climbing safeguard, monotone-quality circular history, exact-delta reversible execution and common visited-state accounting."),        new(
            "demon-based-acceptance-talbi-2009",
            "Demon-Based Acceptance",
            "DemonBasedAcceptanceOptimizer<TSolution,TMove,TUndo>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(C_move + C_eval) per attempted transition; O(C_delta) with an exact move-objective evaluator",
            "O(|solution| + |move| + |undo|); O(1) Demon credit state beyond domain workspace",
            "Any solution representation admitting a stochastic neighborhood and reversible move operator; initial credit is objective-scale dependent",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Acceptance/DemonBasedAcceptanceOptimizer.cs",
            "Talbi (2009), Single-Solution Based Metaheuristics, Metaheuristics: From Design to Implementation, Chapter 2; energy-exchange origin Creutz (1983)",
            "10.1002/9780470496916.ch2",
            "Deterministic conserved-credit Demon acceptance, exact-delta reversible execution, minimization/maximization energy symmetry and common visited-state accounting."),        new(
            "tabu-search-glover",
            "Tabu Search",
            "TabuSearchOptimizer<TSolution,TMove,TUndo,TAttribute,TEnumerator>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(|N(x)| * C_delta + log M) per iteration with exact deltas; otherwise O(|N(x)| * (C_move + C_eval + C_undo) + log M)",
            "O(|solution| + M) for retained short-term tabu records",
            "Any finite enumerated neighborhood with reversible moves and domain-defined tabu attributes",
            true,
            "src/MetaheuristicsPlatform/Algorithms/TS/TabuSearchOptimizer.cs",
            "Glover (1989), Tabu Search-Part I, ORSA Journal on Computing 1(3), 190-206; Glover (1990), Tabu Search-Part II, ORSA Journal on Computing 2(1), 4-32",
            "10.1287/ijoc.1.3.190",
            "Allocation-free neighborhood scan, attribute-based expiration memory, best-so-far aspiration, configurable tenure, exact-delta fast path and reversible full-evaluation fallback."),
        new(
            "reactive-tabu-search-battiti-tecchiolli-1994",
            "Reactive Tabu Search",
            "ReactiveTabuSearchOptimizer<TSolution,TMove,TUndo,TAttribute,TEnumerator>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(|N(x)| * C_delta + log M_s) per normal iteration with exact deltas; escape steps reservoir-scan N(x) and evaluate one selected move",
            "O(|solution| + M_s + M_f + M_r) for short-term, frequency and repetition memories",
            "Finite enumerated neighborhoods with reversible moves, domain-defined tabu attributes and a stable configuration signature",
            true,
            "src/MetaheuristicsPlatform/Algorithms/TS/ReactiveTabuSearchOptimizer.cs",
            "Battiti & Tecchiolli (1994), The Reactive Tabu Search, ORSA Journal on Computing 6(2), 126-140; Glover (1989, 1990)",
            "10.1287/ijoc.6.2.126",
            "Explicit repetition detection, feedback tabu tenure, cycle-length moving average, reactive random-walk escape, optional frequency diversification, optional elite intensification, exact-delta fast path and common OptimizationContext lifecycle."),
        new(
            "local-search-best-improvement",
            "Local Search — Best Improvement",
            "BestImprovementLocalSearchOptimizer<TSolution,TMove,TUndo,TEnumerator>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(|N(x)| C_delta) per descent step with exact deltas; reversible full evaluation otherwise",
            "O(|solution|)",
            "Finite enumerated neighborhoods with reversible moves",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/LocalSearchOptimizers.cs",
            "Talbi (2009), Metaheuristics: From Design to Implementation",
            "10.1002/9780470496916",
            "Steepest-descent best-improvement scan with allocation-free neighborhood cursor, exact-delta fast path and reversible fallback."),
        new(
            "local-search-first-improvement",
            "Local Search — First Improvement",
            "FirstImprovementLocalSearchOptimizer<TSolution,TMove,TUndo,TEnumerator>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(q C_delta) per accepted move, where q is the number of candidates scanned until first improvement",
            "O(|solution|)",
            "Finite ordered neighborhoods with reversible moves",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/LocalSearchOptimizers.cs",
            "Talbi (2009), Metaheuristics: From Design to Implementation",
            "10.1002/9780470496916",
            "First-descent scan that stops immediately at the first strict improving move."),
        new(
            "multi-start-local-search",
            "Multi-Start Local Search",
            "MultiStartLocalSearchOptimizer<TSolution>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(S * (C_init + C_LS)) for S starts; C_LS depends on the composed local search",
            "O(|solution| + local-search workspace)",
            "Any representation with a start generator and compatible reusable local-search procedure",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/RestartIteratedLocalSearchOptimizers.cs",
            "Marti (2003), Multi-Start Methods, Handbook of Metaheuristics, 355-368; Talbi (2009)",
            "10.1007/0-306-48056-5_12",
            "Sequential restart composition reusing the v0.23 local-search engine under one exact OptimizationContext lifecycle."),
        new(
            "iterated-local-search-lourenco-martin-stutzle",
            "Iterated Local Search - Lourenco-Martin-Stutzle",
            "IteratedLocalSearchOptimizer<TSolution>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(C_LS0 + sum_k(C_perturb,k + C_eval,k + C_LS,k))",
            "O(|solution| + local-search workspace)",
            "Any representation with a reusable local search, owned solution cloning and a domain-defined perturbation",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/RestartIteratedLocalSearchOptimizers.cs",
            "Lourenco, Martin & Stutzle (2003), Iterated Local Search, Handbook of Metaheuristics, 320-353; Talbi (2009)",
            "10.1007/0-306-48056-5_11",
            "Canonical initial-local-search / perturb / local-search / accept framework with independent best-so-far ownership."),
        new(
            "iterated-greedy-ruiz-stutzle-2007",
            "Iterated Greedy - Ruiz-Stützle",
            "IteratedGreedyOptimizer<TSolution,TRemoved>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(C_D(d) + C_C(d) + C_eval + C_LS) per destroy-reconstruct cycle",
            "O(|solution| + |removed| + local-search workspace); O(1) core scalar state",
            "Component-decomposable combinatorial solutions admitting partial destruction and complete greedy reconstruction",
            true,
            "src/MetaheuristicsPlatform/Algorithms/IteratedGreedy/IteratedGreedyOptimizer.cs",
            "Ruiz & Stützle (2007), A simple and effective iterated greedy algorithm for the permutation flowshop scheduling problem, EJOR 177(3), 2033-2049; Stützle & Ruiz (2025), Iterated Greedy, Handbook of Heuristics",
            "10.1016/j.ejor.2005.12.009",
            "Generic destruction-reconstruction trajectory with optional reusable local search, strict-improvement or constant-temperature Metropolis acceptance, complete-solution-only evaluation and common OptimizationContext lifecycle."),
        new(
            "large-neighborhood-search-shaw-1998",
            "Large Neighborhood Search - Shaw",
            "LargeNeighborhoodSearchOptimizer<TSolution,TRemoved>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(C_D(q)+C_R(q)+C_f+C_A) per complete destroy-repair-accept cycle",
            "O(|solution|+|removed|) plus domain destroy/repair workspace",
            "Structured discrete or mixed problems admitting a meaningful partial destruction and complete repair pair",
            true,
            "src/MetaheuristicsPlatform/Algorithms/LargeNeighborhoodSearch/LargeNeighborhoodSearchOptimizer.cs",
            "Shaw (1998), Using Constraint Programming and Local Search Methods to Solve Vehicle Routing Problems, CP98, LNCS 1520, 417-431; Pisinger & Ropke (2010), Large Neighborhood Search, Handbook of Metaheuristics",
            "10.1007/3-540-49481-2_30",
            "Generic owned-clone destroy/repair trajectory with complete-candidate-only evaluation, strict-improvement default acceptance, pluggable acceptance and exact incomplete-cycle OptimizationContext accounting."),
        new(
            "adaptive-large-neighborhood-search-ropke-pisinger-2006",
            "Adaptive Large Neighborhood Search - Ropke-Pisinger",
            "AdaptiveLargeNeighborhoodSearchOptimizer<TSolution,TRemoved>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(D+R+C_D(q)+C_R(q)+C_f) per iteration plus O(D+R) at segment boundaries",
            "O(D+R+V) adaptive state plus cloned visited-solution snapshots",
            "Structured discrete or mixed optimization with multiple complementary destroy and repair heuristics",
            true,
            "src/MetaheuristicsPlatform/Algorithms/AdaptiveLargeNeighborhoodSearch/AdaptiveLargeNeighborhoodSearchOptimizer.cs",
            "Ropke & Pisinger (2006), An Adaptive Large Neighborhood Search Heuristic for the Pickup and Delivery Problem with Time Windows, Transportation Science 40(4), 455-472",
            "10.1287/trsc.1050.0135",
            "Independent roulette-wheel destroy/repair selection, novelty-aware sigma rewards, segmented reaction-factor weight adaptation and geometric simulated-annealing acceptance."),
        new(
            "variable-neighborhood-descent",
            "Variable Neighborhood Descent",
            "VariableNeighborhoodDescentOptimizer<TSolution>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(sum_k C_LS,k) per non-improving sweep, with restart to neighborhood 1 after each strict improvement",
            "O(|solution| + max_k W_LS,k)",
            "Any representation with two or more compatible reusable local-search neighborhoods",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/VariableNeighborhoodSearchOptimizers.cs",
            "Mladenovic & Hansen (1997), Variable neighborhood search; Hansen & Mladenovic (2001), Variable neighborhood search: Principles and applications",
            "10.1016/S0377-2217(00)00100-4",
            "Ordered variable-neighborhood descent that restarts at the first neighborhood after strict improvement and reuses the generic local-search procedure contract."),
        new(
            "variable-neighborhood-search-mladenovic-hansen",
            "Variable Neighborhood Search - Mladenovic-Hansen",
            "VariableNeighborhoodSearchOptimizer<TSolution>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(sum_k(C_shake,k + C_eval + C_LS)) per complete non-improving shaking sweep",
            "O(|solution| + local-search workspace)",
            "Any representation with ordered shaking neighborhoods and a compatible reusable local-search procedure",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/VariableNeighborhoodSearchOptimizers.cs",
            "Mladenovic & Hansen (1997), Variable neighborhood search; Hansen & Mladenovic (2001), Variable neighborhood search: Principles and applications",
            "10.1016/S0305-0548(97)00031-2",
            "Canonical basic VNS: shake in N_k, locally improve, accept strict improvement and restart at the first shaking neighborhood."),
        new(
            "guided-local-search-voudouris-tsang-1999",
            "Guided Local Search - Voudouris-Tsang",
            "GuidedLocalSearchOptimizer<TSolution,TMove,TUndo,TMoveEnumerator,TFeature,TFeatureEnumerator>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(|N(x)|*(C_delta_f+C_delta_p)) per guided scan on the full exact-delta fast path; reversible full evaluation and active-feature scans otherwise",
            "O(|solution| + P) where P is the number of distinct penalized features",
            "Any representation with a reversible move neighborhood and domain-defined unique active features with non-negative feature costs",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/GuidedLocalSearchOptimizer.cs",
            "Tsang & Voudouris (1997), Fast local search and guided local search; Voudouris & Tsang (1999), Guided local search and its application to the traveling salesman problem",
            "10.1016/S0377-2217(98)00099-X",
            "Canonical GLS augmented objective and utility penalties, allocation-free move/feature cursors, exact objective-delta and penalty-sum-delta fast paths, and independent original-objective best-so-far ownership."),
        new(
            "reduced-variable-neighborhood-search",
            "Reduced Variable Neighborhood Search",
            "ReducedVariableNeighborhoodSearchOptimizer<TSolution>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(sum_k(C_shake,k + C_eval,k)) per complete non-improving shaking sweep",
            "O(|solution|)",
            "Any representation with ordered shaking neighborhoods; especially useful when repeated local improvement is too expensive",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/AdvancedVariableNeighborhoodSearchOptimizers.cs",
            "Hansen & Mladenovic (2001); Hansen, Mladenovic, Todosijevic & Hanafi (2017)",
            "10.1007/s13675-016-0075-x",
            "Canonical RVNS: VNS shaking and neighborhood change with the local-improvement phase deliberately omitted."),
        new(
            "general-variable-neighborhood-search",
            "General Variable Neighborhood Search",
            "GeneralVariableNeighborhoodSearchOptimizer<TSolution>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(sum_k(C_shake,k + C_eval,k + C_VND,k)) per complete non-improving shaking sweep",
            "O(|solution| + VND workspace)",
            "Any representation with ordered shaking neighborhoods plus compatible reusable local-search neighborhoods",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/AdvancedVariableNeighborhoodSearchOptimizers.cs",
            "Hansen & Mladenovic (2001); Hansen, Mladenovic, Todosijevic & Hanafi (2017)",
            "10.1007/s13675-016-0075-x",
            "Canonical GVNS: shaking followed by reusable Variable Neighborhood Descent and strict-improvement neighborhood change."),
        new(
            "skewed-variable-neighborhood-search-hansen-mladenovic-2001",
            "Skewed Variable Neighborhood Search - Hansen-Mladenovic",
            "SkewedVariableNeighborhoodSearchOptimizer<TSolution>",
            "trajectory-based-methods",
            "Trajectory-based methods",
            "O(sum_k(C_shake,k + C_eval,k + C_LS,k + C_distance,k)) per complete non-accepting sweep",
            "O(|solution| + local-search workspace)",
            "Any representation with shaking, reusable local search and a finite non-negative domain distance",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Neighborhood/AdvancedVariableNeighborhoodSearchOptimizers.cs",
            "Hansen & Mladenovic (2001), Variable neighborhood search: Principles and applications; Hansen et al. (2017)",
            "10.1016/S0377-2217(00)00100-4",
            "Canonical SVNS recentering with a distance-skewed objective comparison while preserving original-objective best-so-far."),
        new(
            "grasp-feo-resende-1995",
            "GRASP - Feo-Resende",
            "GraspOptimizer<TSolution>",
            "constructive-methods",
            "Constructive methods",
            "O(2 * sum_t |C_t| * C_g + C_eval + C_LS) per outer iteration",
            "O(|solution| + construction cursor + local-search workspace); RCL overhead O(1)",
            "Constructive optimization problems with a domain greedy score, restartable candidate cursor and compatible reusable local search",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Constructive/GraspOptimizer.cs",
            "Feo & Resende (1989), Operations Research Letters 8(2), 67-71; Feo & Resende (1995), Journal of Global Optimization 6(2), 109-133",
            "10.1007/BF01096763",
            "Canonical adaptive threshold-RCL construction with allocation-free two-pass scans and uniform reservoir selection, followed by reusable local search under one OptimizationContext lifecycle."),
        new(
            "reactive-grasp-prais-ribeiro-2000",
            "Reactive GRASP - Prais-Ribeiro",
            "ReactiveGraspOptimizer<TSolution>",
            "constructive-methods",
            "Constructive methods",
            "Canonical GRASP construction/local-search cost plus O(m) alpha sampling and periodic O(m) probability updates",
            "Canonical GRASP workspace plus O(m) reactive alpha statistics",
            "Constructive optimization problems with positive objective values, a GRASP construction model and compatible reusable local search",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Constructive/ReactiveGraspOptimizer.cs",
            "Prais & Ribeiro (2000), Reactive GRASP: An Application to a Matrix Decomposition Problem in TDMA Traffic Assignment, INFORMS Journal on Computing 12(3), 164-176",
            "10.1287/ijoc.12.3.164.12639",
            "Discrete alpha probabilities start uniformly and are periodically updated from per-alpha average locally improved solution quality using the Prais-Ribeiro ratio rule."),
        new(
            "grasp-path-relinking",
            "GRASP with Path Relinking",
            "GraspPathRelinkingOptimizer<TSolution>",
            "constructive-methods",
            "Constructive methods",
            "Canonical GRASP + online pairwise PR; optional EvPR adds O(E^2*C_PR) per evolutionary generation plus optional offspring local-search cost",
            "O(E*|solution| + path workspace); EvPR keeps bounded current/next elite populations and pooled randomized-path probes",
            "Finite attribute-based path spaces with GRASP construction, compatible local search, integral non-negative distance and target-directed reversible moves",
            true,
            "src/MetaheuristicsPlatform/Algorithms/Constructive/GraspPathRelinkingOptimizer.cs",
            "Resende & Werneck (2004), Journal of Heuristics 10(1), 59-88; Aiex, Resende, Pardalos & Toraldo (2005), INFORMS Journal on Computing 17(2), 224-247; Resende, Marti, Gallego & Duarte (2010), Computers & Operations Research 37(3), 498-508; Ribeiro & Resende (2012), Journal of Heuristics 18(2), 193-214",
            "10.1287/ijoc.1030.0059",
            "Quality/diversity elite memory, advanced forward/backward/back-and-forward/mixed pairwise path relinking, truncation, greedy-randomized pooled RCL selection, and optional EvolutionaryPathRelinkingProcedure<TSolution> all-pairs elite evolution."),
        new(
            "biogeography-based-optimization-simon-2008",
            "Biogeography-Based Optimization",
            "BiogeographyBasedOptimizationOptimizer",
            "evolutionary-methods",
            "Evolutionary methods",
            "O(N log N + N^2 D) per generation plus objective-evaluation cost",
            "O(ND + N)",
            "Bounded continuous derivative-free optimization using rank-based immigration, emigration, mutation and elitism",
            false,
            "src/MetaheuristicsPlatform/Algorithms/BiogeographyBasedOptimization/BiogeographyBasedOptimizationOptimizer.cs",
            "Simon (2008), Biogeography-Based Optimization, IEEE Transactions on Evolutionary Computation 12(6), 702-713",
            "10.1109/TEVC.2008.919004",
            "Canonical rank-derived species counts, linear immigration/emigration curves, equilibrium species-probability mutation, explicit elitism and bounded SIV repair."),
        new(
            "cuckoo-search-yang-deb-2009",
            "Cuckoo Search via Levy Flights",
            "CuckooSearchOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(D + N log N + p_a N D) per published generation plus objective-evaluation cost",
            "O(ND + N)",
            "Bounded continuous derivative-free optimization with Levy-flight exploration and nest abandonment",
            false,
            "src/MetaheuristicsPlatform/Algorithms/CuckooSearch/CuckooSearchOptimizer.cs",
            "Yang & Deb (2009), Cuckoo Search via Levy Flights, NaBIC 2009, 210-214",
            "10.1109/NABIC.2009.5393690",
            "Published Yang-Deb pseudocode: one randomly chosen cuckoo Levy-flight proposal, random host-nest comparison, replacement of a p_a fraction of worst nests by new random nests, elitist retention and ranking. The Levy-flight operator is realized internally with Mantegna's symmetric beta=1.5 construction; beta is intentionally not exposed as a configurable public parameter for this canonical identity."),
        new(
            "bat-algorithm-yang-2010",
            "Bat Algorithm",
            "BatAlgorithmOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(ND) per generation plus N objective evaluations",
            "O(ND + N)",
            "Bounded continuous derivative-free optimization with frequency-tuned motion, pulse-rate local search and loudness acceptance",
            false,
            "src/MetaheuristicsPlatform/Algorithms/BatAlgorithm/BatAlgorithmOptimizer.cs",
            "Yang (2010), A New Metaheuristic Bat-Inspired Algorithm, NICSO 2010, 65-74",
            "10.1007/978-3-642-12538-6_6",
            "Canonical frequency/velocity/position update, best-centered local random walk, loudness-gated greedy acceptance, geometric loudness decay and asymptotic pulse-rate growth."),
        new(
            "flower-pollination-algorithm-yang-2012",
            "Flower Pollination Algorithm",
            "FlowerPollinationOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(ND) per generation plus N objective evaluations",
            "O(ND + N)",
            "Bounded continuous derivative-free optimization mixing global Levy pollination and local flower constancy",
            false,
            "src/MetaheuristicsPlatform/Algorithms/FlowerPollination/FlowerPollinationOptimizer.cs",
            "Yang (2012), Flower Pollination Algorithm for Global Optimization, UCNC 2012, LNCS 7445, 240-249",
            "10.1007/978-3-642-32894-7_27",
            "Canonical switch-controlled global Levy pollination toward the current best and local random flower-pair pollination with greedy replacement. The Levy-flight operator uses a fixed internal Mantegna beta=1.5 numerical realization rather than exposing a later variant parameter."),
        new(
            "grey-wolf-optimizer-mirjalili-mirjalili-lewis-2014",
            "Grey Wolf Optimizer",
            "GreyWolfOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(ND + N log N) per generation plus N objective evaluations",
            "O(ND + N)",
            "Bounded continuous derivative-free optimization using alpha/beta/delta leadership and encircling dynamics",
            false,
            "src/MetaheuristicsPlatform/Algorithms/GreyWolf/GreyWolfOptimizer.cs",
            "Mirjalili, Mirjalili & Lewis (2014), Grey Wolf Optimizer, Advances in Engineering Software 69, 46-61",
            "10.1016/j.advengsoft.2013.12.007",
            "Canonical alpha-beta-delta leadership, three independent A/C encircling vectors, arithmetic mean position update and linear a decrease from 2 to 0."),
        new(
            "moth-flame-optimization-mirjalili-2015",
            "Moth-Flame Optimization",
            "MothFlameOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(ND + N log N) per generation plus N objective evaluations",
            "O(ND + N)",
            "Bounded continuous derivative-free optimization with logarithmic moth-to-flame spirals and a linearly decreasing flame count",
            false,
            "src/MetaheuristicsPlatform/Algorithms/MothFlame/MothFlameOptimizer.cs",
            "Mirjalili (2015), Moth-flame optimization algorithm: A novel nature-inspired heuristic paradigm, Knowledge-Based Systems 89, 228-249",
            "10.1016/j.knosys.2015.07.006",
            "Canonical moth/flame dual population, historical flame elitism, logarithmic spiral update, and linearly decreasing flame count from Mirjalili (2015)."),
        new(
            "whale-optimization-algorithm-mirjalili-lewis-2016",
            "Whale Optimization Algorithm",
            "WhaleOptimizationAlgorithmOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(ND) per generation plus N objective evaluations",
            "O(ND + N)",
            "Bounded continuous derivative-free optimization with encircling, random-prey exploration and logarithmic bubble-net spirals",
            false,
            "src/MetaheuristicsPlatform/Algorithms/WhaleOptimization/WhaleOptimizationAlgorithmOptimizer.cs",
            "Mirjalili & Lewis (2016), The Whale Optimization Algorithm, Advances in Engineering Software 95, 51-67",
            "10.1016/j.advengsoft.2016.01.008",
            "Canonical WOA with scalar A/C coefficients per whale, random-prey exploration for |A|>=1, best-prey encircling for |A|<1, and the 50/50 logarithmic spiral mechanism."),
        new(
            "sine-cosine-algorithm-mirjalili-2016",
            "Sine Cosine Algorithm",
            "SineCosineAlgorithmOptimizer",
            "swarm-intelligence",
            "Swarm intelligence",
            "O(ND) per generation plus N objective evaluations",
            "O(ND + N)",
            "Bounded continuous derivative-free optimization with sine/cosine oscillation around the best destination",
            false,
            "src/MetaheuristicsPlatform/Algorithms/SineCosine/SineCosineAlgorithmOptimizer.cs",
            "Mirjalili (2016), SCA: A Sine Cosine Algorithm for solving optimization problems, Knowledge-Based Systems 96, 120-133",
            "10.1016/j.knosys.2015.12.022",
            "Canonical SCA with linearly decreasing r1, r2 in [0,2pi), r3 in [0,2), and an equiprobable sine/cosine switch r4.")
    ];

    private static readonly IReadOnlyDictionary<string, MetaheuristicCatalogEntry>
        ById =
        Entries.ToDictionary(
            static entry => entry.Id,
            StringComparer.Ordinal);

    public static IReadOnlyList<MetaheuristicCatalogEntry> All =>
        Entries;

    public static bool TryGet(
        string id,
        out MetaheuristicCatalogEntry? entry)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(id);

        return ById.TryGetValue(
            id,
            out entry);
    }

    public static MetaheuristicCatalogEntry GetRequired(
        string id)
    {
        if (!TryGet(
                id,
                out MetaheuristicCatalogEntry? entry))
        {
            throw new KeyNotFoundException(
                $"Unknown metaheuristic algorithm id '{id}'.");
        }

        return entry!;
    }
}
