using MetaheuristicsPlatform.Algorithms.Neighborhood;
using MetaheuristicsPlatform.Callbacks;
using MetaheuristicsPlatform.Classification;
using MetaheuristicsPlatform.Core;
using MetaheuristicsPlatform.Stopping;

namespace MetaheuristicsPlatform.Algorithms.Constructive;

/// <summary>
/// GRASP with an elite pool and path relinking.
/// Every GRASP solution is locally improved before it is considered for relinking.
/// Relinking is performed against an elite solution generated by an earlier iteration,
/// then the best visited path solution is considered for the elite pool.
/// </summary>
public sealed class GraspPathRelinkingOptimizer<TSolution> :
    IMetaheuristic<TSolution, GraspPathRelinkingParameters>
{
    private readonly IGraspConstructionProcedure<TSolution> _construction;
    private readonly ILocalSearchProcedure<TSolution> _localSearch;
    private readonly IPathRelinkingProcedure<TSolution> _pathRelinking;
    private readonly IPathRelinkingDistance<TSolution> _distance;

    /// <summary>Creates a GRASP + Path Relinking composition.</summary>
    public GraspPathRelinkingOptimizer(
        IGraspConstructionProcedure<TSolution> construction,
        ILocalSearchProcedure<TSolution> localSearch,
        IPathRelinkingProcedure<TSolution> pathRelinking,
        IPathRelinkingDistance<TSolution> distance)
    {
        _construction =
            construction ?? throw new ArgumentNullException(nameof(construction));
        _localSearch =
            localSearch ?? throw new ArgumentNullException(nameof(localSearch));
        _pathRelinking =
            pathRelinking ?? throw new ArgumentNullException(nameof(pathRelinking));
        _distance =
            distance ?? throw new ArgumentNullException(nameof(distance));
    }

    /// <inheritdoc />
    public MetaheuristicDescriptor Descriptor { get; } = new()
    {
        Id = "grasp-path-relinking",
        Name = "GRASP with Path Relinking",
        Acronym = "GRASP-PR",
        SolutionModel = MetaheuristicSolutionModel.SingleSolution,
        Families =
            MetaheuristicFamily.Constructive |
            MetaheuristicFamily.LocalSearch |
            MetaheuristicFamily.Hybrid,
        Mechanisms =
            MetaheuristicMechanism.Constructive |
            MetaheuristicMechanism.Neighborhood |
            MetaheuristicMechanism.MemoryBased |
            MetaheuristicMechanism.Hybrid,
        SearchSpaces =
            SearchSpaceKind.Binary |
            SearchSpaceKind.Integer |
            SearchSpaceKind.Permutation |
            SearchSpaceKind.Combinatorial |
            SearchSpaceKind.Mixed,
        IsStochastic = true,
        References =
        [
            GraspReferences.FeoResende1995,
            GraspReferences.ResendeRibeiro2003,
            GraspReferences.AiexResendePardalosToraldo2005,
            GraspReferences.RibeiroResende2012
        ]
    };

    /// <inheritdoc />
    public GraspPathRelinkingParameters CreateDefaultParameters() => new();

    /// <inheritdoc />
    public OptimizationResult<TSolution> Optimize(
        IOptimizationProblem<TSolution> problem,
        GraspPathRelinkingParameters parameters,
        ISolutionCloner<TSolution> solutionCloner,
        IStoppingCriterion stoppingCriterion,
        OptimizationOptions? options = null,
        IOptimizationCallback<TSolution>? callback = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(problem);
        ArgumentNullException.ThrowIfNull(parameters);
        ArgumentNullException.ThrowIfNull(solutionCloner);
        ArgumentNullException.ThrowIfNull(stoppingCriterion);

        parameters.Validate();

        PathRelinkingExecutionOptions pathRelinkingOptions =
            parameters.CreatePathRelinkingExecutionOptions();

        if (!pathRelinkingOptions.IsCanonicalGreedyForward &&
            _pathRelinking is not IAdvancedPathRelinkingProcedure<TSolution>)
        {
            throw new InvalidOperationException(
                "Advanced path-relinking parameters require an " +
                "IAdvancedPathRelinkingProcedure<TSolution> implementation.");
        }

        var context = new OptimizationContext<TSolution>(
            Descriptor,
            problem,
            solutionCloner,
            stoppingCriterion,
            options,
            callback,
            cancellationToken);

        var elitePool = new EliteSolutionPool<TSolution>(
            parameters.ElitePoolSize,
            parameters.MinimumEliteDistance,
            _distance,
            problem,
            solutionCloner);

        var state = new GraspPathRelinkingState(
            OuterIterationsCompleted: 0,
            ConstructionSteps: 0,
            GreedyScoreEvaluations: 0,
            AcceptedLocalMoves: 0,
            PathRelinkingInvocations: 0,
            PathSteps: 0,
            PathCandidateEvaluations: 0,
            ElitePoolCount: 0,
            ElitePoolUpdates: 0);

        context.Start(state);

        long totalConstructionSteps = 0;
        long totalGreedyScoreEvaluations = 0;
        long totalAcceptedLocalMoves = 0;
        long pathRelinkingInvocations = 0;
        long totalPathSteps = 0;
        long totalPathCandidateEvaluations = 0;
        long elitePoolUpdates = 0;

        for (int outerIteration = 1;
             outerIteration <= parameters.MaximumIterations;
             outerIteration++)
        {
            cancellationToken.ThrowIfCancellationRequested();

            GraspConstructionResult<TSolution> constructionResult =
                _construction.Construct(
                    problem,
                    context.Random,
                    parameters.Alpha,
                    parameters.MaximumConstructionSteps,
                    cancellationToken);

            totalConstructionSteps +=
                constructionResult.ConstructionSteps;
            totalGreedyScoreEvaluations +=
                constructionResult.GreedyScoreEvaluations;

            TSolution solution =
                constructionResult.Solution;

            state = CreateState(
                outerIteration - 1,
                totalConstructionSteps,
                totalGreedyScoreEvaluations,
                totalAcceptedLocalMoves,
                pathRelinkingInvocations,
                totalPathSteps,
                totalPathCandidateEvaluations,
                elitePool.Count,
                elitePoolUpdates);

            double fitness =
                context.Evaluate(
                    solution,
                    state);

            StoppingDecision stop =
                context.EvaluateStopping(state);

            if (stop.ShouldStop)
            {
                return context.Complete(stop, state);
            }

            LocalSearchProcedureResult localResult =
                _localSearch.Improve(
                    ref solution,
                    fitness,
                    context,
                    solutionCloner,
                    cancellationToken);

            fitness = localResult.Fitness;
            totalAcceptedLocalMoves +=
                localResult.AcceptedMoves;

            if (localResult.StoppingDecision.ShouldStop)
            {
                state = CreateState(
                    outerIteration - 1,
                    totalConstructionSteps,
                    totalGreedyScoreEvaluations,
                    totalAcceptedLocalMoves,
                    pathRelinkingInvocations,
                    totalPathSteps,
                    totalPathCandidateEvaluations,
                    elitePool.Count,
                    elitePoolUpdates);

                return context.Complete(
                    localResult.StoppingDecision,
                    state);
            }

            if (elitePool.TrySelectGuide(
                    in solution,
                    context.Random,
                    out TSolution guidingSolution,
                    out double guidingFitness))
            {
                pathRelinkingInvocations++;

                PathRelinkingProcedureResult<TSolution> relinkingResult;

                if (_pathRelinking is IAdvancedPathRelinkingProcedure<TSolution> advancedPathRelinking)
                {
                    relinkingResult =
                        advancedPathRelinking.RelinkAdvanced(
                            in solution,
                            fitness,
                            in guidingSolution,
                            guidingFitness,
                            pathRelinkingOptions,
                            context,
                            solutionCloner,
                            parameters.MaximumPathSteps,
                            cancellationToken);
                }
                else
                {
                    relinkingResult =
                        _pathRelinking.Relink(
                            in solution,
                            fitness,
                            in guidingSolution,
                            context,
                            solutionCloner,
                            parameters.MaximumPathSteps,
                            cancellationToken);
                }

                totalPathSteps +=
                    relinkingResult.PathSteps;
                totalPathCandidateEvaluations +=
                    relinkingResult.CandidateEvaluations;

                if (relinkingResult.StoppingDecision.ShouldStop)
                {
                    state = CreateState(
                        outerIteration - 1,
                        totalConstructionSteps,
                        totalGreedyScoreEvaluations,
                        totalAcceptedLocalMoves,
                        pathRelinkingInvocations,
                        totalPathSteps,
                        totalPathCandidateEvaluations,
                        elitePool.Count,
                        elitePoolUpdates);

                    return context.Complete(
                        relinkingResult.StoppingDecision,
                        state);
                }

                solution =
                    relinkingResult.BestSolution;
                fitness =
                    relinkingResult.BestFitness;
            }

            if (elitePool.TryAdd(
                    in solution,
                    fitness,
                    out _))
            {
                elitePoolUpdates++;
            }

            state = CreateState(
                outerIteration,
                totalConstructionSteps,
                totalGreedyScoreEvaluations,
                totalAcceptedLocalMoves,
                pathRelinkingInvocations,
                totalPathSteps,
                totalPathCandidateEvaluations,
                elitePool.Count,
                elitePoolUpdates);

            context.CompleteIteration(
                fitness,
                state);

            stop =
                context.EvaluateStopping(state);

            if (stop.ShouldStop)
            {
                return context.Complete(stop, state);
            }
        }

        return context.Complete(
            StoppingDecision.Stop(
                "MaximumGraspPathRelinkingIterations",
                "The configured GRASP Path Relinking outer-iteration limit was reached."),
            CreateState(
                parameters.MaximumIterations,
                totalConstructionSteps,
                totalGreedyScoreEvaluations,
                totalAcceptedLocalMoves,
                pathRelinkingInvocations,
                totalPathSteps,
                totalPathCandidateEvaluations,
                elitePool.Count,
                elitePoolUpdates));
    }

    private static GraspPathRelinkingState CreateState(
        int outerIterationsCompleted,
        long constructionSteps,
        long greedyScoreEvaluations,
        long acceptedLocalMoves,
        long pathRelinkingInvocations,
        long pathSteps,
        long pathCandidateEvaluations,
        int elitePoolCount,
        long elitePoolUpdates) =>
        new(
            outerIterationsCompleted,
            constructionSteps,
            greedyScoreEvaluations,
            acceptedLocalMoves,
            pathRelinkingInvocations,
            pathSteps,
            pathCandidateEvaluations,
            elitePoolCount,
            elitePoolUpdates);
}

/// <summary>Observable state for GRASP with Path Relinking.</summary>
public readonly record struct GraspPathRelinkingState(
    int OuterIterationsCompleted,
    long ConstructionSteps,
    long GreedyScoreEvaluations,
    long AcceptedLocalMoves,
    long PathRelinkingInvocations,
    long PathSteps,
    long PathCandidateEvaluations,
    int ElitePoolCount,
    long ElitePoolUpdates);